version: '3.7'

services:
  blog:
    platform: linux/amd64
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5438:5432
    volumes:
      - ./pg_blog:/var/lib/postgresql/data