version: "2.1"

services:
  blog-db:
    platform: linux/amd64
    image: postgres:13.5-alpine
    container_name: blog-db
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres 
    restart: unless-stopped
    ports:
      - 5436:5432
    volumes:
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:ro
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro